apiVersion: v2
name: livemart
description: LiveMart MSA E-Commerce Platform Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: LiveMart Team
    email: dev@livemart.com
keywords:
  - msa
  - ecommerce
  - spring-boot
  - kubernetes
